# Default Values
port = 7497
host = "127.0.0.1"
data_type = 4
instrument = "SPX"
exchange = "SMART"
currency = "USD"
strike_interval = 5
STP_enabled = True
close_positions = False
enable_logging = True
calc_values = True
close_hedges = True
WEBHOOK_URL = "https://discord.com/api/webhooks/1338550862922125382/ngLa-LmVaolmdMDeNV4f4jTEhzhCJwvZXsSrpHiYcZmWIhYEQ9ef4elRQB0Kf1PmYG5B"

# Changeable Values
date = "20250606"                   # Date of contract (YYYY-MM-DD)
CE_SELL_REENTRY = 1
CE_BUY_REENTRY = 1
PE_SELL_REENTRY = 1
PE_BUY_REENTRY = 1
OTM_CALL_HEDGE = 10                # How far away the call hedge is (10 means that its $50 away from current price)
OTM_PUT_HEDGE = 10                 # How far away the put hedge is (10 means that its $50 away from current price)
ATM_CALL = 5                        # How far away call position is (2 means that its $10 away from current price)
ATM_PUT = 5                         # How far away put position is (2 means that its $10 away from current price)
call_sl = 30                        # From where the call stop loss should start from (15 here means 15% of entry price)
call_entry_price_changes_by = 10     # What % should call entry premium price should change by to update the trailing %
call_change_sl_by = 10               # What % of entry price should call sl change when trailing stop loss updates
put_sl = 30                         # From where the put stop loss should start from (15 here means 15% of entry price)
put_entry_price_changes_by = 10      # What % should put entry premium price should change by to update the trailing %
put_change_sl_by = 10                # What % of entry price should put sl change when trailing stop loss updates
conversion_time = 10                # Deprecated (No use)
entry_hour = 9                      # Entry time in hours
entry_minute = 30                   # Entry time in minutes
entry_second = 59                    # Entry time in seconds
exit_hour = 14                     # Exit time in hours
exit_minute = 30                    # Exit time in minutes
exit_second = 00                     # Exit time in seconds
call_hedge_quantity = 1             # Quantity for call hedge
put_hedge_quantity = 1              # Quantity for put hedge
call_position = 1                   # Quantity for call position
put_position = 1                    # Quantity for put position
call_hedge = 19510
call_strike = 19500
put_hedge = 19490
put_strike = 19500
call_check_time = 1
put_check_time = 1

